name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe the behaviour you're expecting
      placeholder: When I do ... then ... should happen
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps for repoducing the issue
      placeholder: |
        1. Open
        2. Run
        3. Test
    validations:
      required: true
  - type: textarea
    id: detailed-description
    attributes:
      label: Detailed Description
      description: Provide information about the failure.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Windows 10, Arch Linux, MacOS, etc
      placeholder: Arch Linux
    validations:
      required: true
